# -*- coding: utf-8 -*-
"""LoadEmbedding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yXa1LvxUVSFtg9iFXuWeDLxEa_K9pYWz
"""

import gensim
from gensim.models.keyedvectors import KeyedVectors

def load_vector():
    from google.colab import drive
    drive.mount('/content/drive')
    base_folder = 'drive/My Drive/dataset/NepaliEmbed/'
    word_vector = KeyedVectors.load(base_folder + 'word_vector.sg')
    return word_vector



